<?php

namespace AppBundle\Repository;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class EvaluationRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByAverageProd($prod_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT AVG(p.rate) FROM AppBundle:Evaluation p WHERE p.prod = '.$prod_id
            )
            ->getResult();
    }

    public function findByAllAverageProd()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT IDENTITY(p.prod), AVG(p.rate) as avg_rate FROM AppBundle:Evaluation p GROUP BY p.prod ORDER BY avg_rate DESC'
            )
            ->getResult();
    }
}
